# Generated by Django 4.0 on 2022-03-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cust',
            fields=[
                ('custid', models.IntegerField(primary_key=True, serialize=False)),
                ('passwd', models.TextField(default='', max_length=20)),
                ('name', models.TextField(default='', max_length=20)),
                ('balance', models.IntegerField(default=0)),
                ('opendate', models.DateField(default='')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='trans',
            fields=[
                ('transid', models.IntegerField(primary_key=True, serialize=False)),
                ('receiver', models.IntegerField(default=0)),
                ('amt', models.IntegerField(default=0)),
                ('status', models.TextField(default='')),
                ('dot', models.DateField(default='')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.cust')),
            ],
        ),
    ]
