# Generated by Django 4.0 on 2022-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cust_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust',
            name='passwd',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trans',
            name='receiver',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
